[package]
name = "lumio-types"

edition = "2021"
version = "0.1.0"

[dependencies]
borsh = { version = "1.2.1", features = ["derive", "unstable__schema"] }
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.9.0"
sha3 = "0.11.0-pre.3"

[dev-dependencies]
serde_json = "1.0"
rand = "0.8"
