[package]
name = "lumio-types"

edition = "2021"
version = "0.1.0"

[dependencies]
borsh = { version = "1", features = ["derive"] }
hex = "0.4"
serde = { version = "1", features = ["derive"] }
sha3 = "0.11.0-pre.3"
jsonrpsee = { version = "0.22", features = ["server-core", "client-core", "macros"]}

[dev-dependencies]
serde_json = "1.0"
rand = "0.8"
