[workspace]
resolver = "2"

members = [
  "rpc",
  "types",
  "payload-builder",
]

[workspace.package]
edition = "2021"
name = "lumio-common"
version = "0.1.0"

[workspace.dependencies]
lumio-payload-builder = {path = "payload-builder"}
lumio-rpc = {path = "rpc"}
lumio-types = {path = "types"}

anyhow = "1.0.82"
borsh = {version = "1", features = ["derive"]}
derive_more = "0.99"
futures = "0.3.30"
hex = "0.4"
jsonrpsee = {version = "0.24", features = ["server-core", "client-core", "macros"]}
log = "0.4.14"
rand = "0.8"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
serde_with = {version = "3", features = ["base64"]}
sha3 = "0.10"
tokio = {version = "1.29.1", features = ["rt"]}
strum = {version = "0.21", features = ["derive"]}

[workspace.lints.rust]
unused_crate_dependencies = "warn"
