[package]
name = "lumio-types"

edition = "2021"
version = "0.1.0"

[dependencies]
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.9.0"
borsh = "0.9.0"

[dev-dependencies]
serde_json = "1.0"
rand = "0.8"
