[package]
name = "lumio-rpc"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
eyre.workspace = true
hex.workspace = true
jsonwebtoken.workspace = true
poem = {workspace = true, features = ["eyre06"]}
poem-grants.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
lumio-types.workspace = true

[dev-dependencies]
tokio = {workspace = true, features = ["test-util", "macros"]}

[lints]
workspace = true
